# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_seat.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1349, 638)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_start = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.button_start.setFont(font)
        self.button_start.setObjectName("button_start")
        self.horizontalLayout_3.addWidget(self.button_start)
        self.button_stop = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.button_stop.setFont(font)
        self.button_stop.setObjectName("button_stop")
        self.horizontalLayout_3.addWidget(self.button_stop)
        spacerItem = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.button_save_to = QtWidgets.QPushButton(Form)
        self.button_save_to.setObjectName("button_save_to")
        self.horizontalLayout_3.addWidget(self.button_save_to)
        self.button_replay = QtWidgets.QPushButton(Form)
        self.button_replay.setObjectName("button_replay")
        self.horizontalLayout_3.addWidget(self.button_replay)
        self.replay_time = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.replay_time.sizePolicy().hasHeightForWidth())
        self.replay_time.setSizePolicy(sizePolicy)
        self.replay_time.setBaseSize(QtCore.QSize(0, 0))
        self.replay_time.setObjectName("replay_time")
        self.horizontalLayout_3.addWidget(self.replay_time)
        self.button_replay_goto = QtWidgets.QPushButton(Form)
        self.button_replay_goto.setObjectName("button_replay_goto")
        self.horizontalLayout_3.addWidget(self.button_replay_goto)
        spacerItem1 = QtWidgets.QSpacerItem(188, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_load_calibration = QtWidgets.QPushButton(Form)
        self.button_load_calibration.setObjectName("button_load_calibration")
        self.verticalLayout_2.addWidget(self.button_load_calibration)
        self.button_exit_calibration = QtWidgets.QPushButton(Form)
        self.button_exit_calibration.setObjectName("button_exit_calibration")
        self.verticalLayout_2.addWidget(self.button_exit_calibration)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button_set_zero = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.button_set_zero.setFont(font)
        self.button_set_zero.setObjectName("button_set_zero")
        self.verticalLayout_6.addWidget(self.button_set_zero)
        self.button_abandon_zero = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.button_abandon_zero.setFont(font)
        self.button_abandon_zero.setObjectName("button_abandon_zero")
        self.verticalLayout_6.addWidget(self.button_abandon_zero)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fig_image_0 = GraphicsLayoutWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fig_image_0.sizePolicy().hasHeightForWidth())
        self.fig_image_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        self.fig_image_0.setFont(font)
        self.fig_image_0.setObjectName("fig_image_0")
        self.horizontalLayout.addWidget(self.fig_image_0)
        self.fig_lines = GraphicsLayoutWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fig_lines.sizePolicy().hasHeightForWidth())
        self.fig_lines.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        self.fig_lines.setFont(font)
        self.fig_lines.setObjectName("fig_lines")
        self.horizontalLayout.addWidget(self.fig_lines)
        self.horizontalLayout.setStretch(0, 4)
        self.horizontalLayout.setStretch(1, 3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_output = QtWidgets.QLabel(Form)
        self.label_output.setText("")
        self.label_output.setObjectName("label_output")
        self.verticalLayout.addWidget(self.label_output)
        self.label_fixed = QtWidgets.QLabel(Form)
        self.label_fixed.setObjectName("label_fixed")
        self.verticalLayout.addWidget(self.label_fixed)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/logo/LOGO.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_start.setText(_translate("Form", "开始"))
        self.button_stop.setText(_translate("Form", "停止"))
        self.button_save_to.setText(_translate("Form", "采集到..."))
        self.button_replay.setText(_translate("Form", "重放..."))
        self.replay_time.setText(_translate("Form", "0"))
        self.button_replay_goto.setText(_translate("Form", "跳转"))
        self.button_load_calibration.setText(_translate("Form", "加载标定文件..."))
        self.button_exit_calibration.setText(_translate("Form", "去除标定"))
        self.button_set_zero.setText(_translate("Form", "零点修正"))
        self.button_abandon_zero.setText(_translate("Form", "去除修正"))
        self.label_fixed.setText(_translate("Form", "电子皮肤显示程序V1.2  途见科技（北京）有限公司"))

from pyqtgraph import GraphicsLayoutWidget
