# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 720)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_start = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.button_start.setFont(font)
        self.button_start.setObjectName("button_start")
        self.horizontalLayout.addWidget(self.button_start)
        self.button_stop = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.button_stop.setFont(font)
        self.button_stop.setObjectName("button_stop")
        self.horizontalLayout.addWidget(self.button_stop)
        spacerItem = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.combo_filter_frame = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.combo_filter_frame.setFont(font)
        self.combo_filter_frame.setObjectName("combo_filter_frame")
        self.combo_filter_frame.addItem("")
        self.combo_filter_frame.addItem("")
        self.combo_filter_frame.addItem("")
        self.combo_filter_frame.addItem("")
        self.verticalLayout_3.addWidget(self.combo_filter_frame)
        self.combo_filter_time = QtWidgets.QComboBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.combo_filter_time.setFont(font)
        self.combo_filter_time.setObjectName("combo_filter_time")
        self.combo_filter_time.addItem("")
        self.combo_filter_time.addItem("")
        self.combo_filter_time.addItem("")
        self.combo_filter_time.addItem("")
        self.combo_filter_time.addItem("")
        self.combo_filter_time.addItem("")
        self.combo_filter_time.addItem("")
        self.combo_filter_time.addItem("")
        self.combo_filter_time.addItem("")
        self.verticalLayout_3.addWidget(self.combo_filter_time)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.button_set_zero = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.button_set_zero.setFont(font)
        self.button_set_zero.setObjectName("button_set_zero")
        self.verticalLayout_2.addWidget(self.button_set_zero)
        self.button_abandon_zero = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.button_abandon_zero.setFont(font)
        self.button_abandon_zero.setObjectName("button_abandon_zero")
        self.verticalLayout_2.addWidget(self.button_abandon_zero)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fig_image = GraphicsLayoutWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fig_image.sizePolicy().hasHeightForWidth())
        self.fig_image.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        self.fig_image.setFont(font)
        self.fig_image.setObjectName("fig_image")
        self.horizontalLayout_2.addWidget(self.fig_image)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.fig_0 = GraphicsLayoutWidget(Form)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        self.fig_0.setFont(font)
        self.fig_0.setObjectName("fig_0")
        self.verticalLayout.addWidget(self.fig_0)
        spacerItem3 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.fig_1 = GraphicsLayoutWidget(Form)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        self.fig_1.setFont(font)
        self.fig_1.setObjectName("fig_1")
        self.verticalLayout.addWidget(self.fig_1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem4)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.fig_2 = GraphicsLayoutWidget(Form)
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(16)
        self.fig_2.setFont(font)
        self.fig_2.setObjectName("fig_2")
        self.verticalLayout.addWidget(self.fig_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.console_out = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.console_out.setFont(font)
        self.console_out.setText("")
        self.console_out.setObjectName("console_out")
        self.gridLayout.addWidget(self.console_out, 2, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.button_start.setText(_translate("Form", "开始"))
        self.button_stop.setText(_translate("Form", "停止"))
        self.label_6.setText(_translate("Form", "滤波器"))
        self.combo_filter_frame.setItemText(0, _translate("Form", "无"))
        self.combo_filter_frame.setItemText(1, _translate("Form", "并联抵消-轻"))
        self.combo_filter_frame.setItemText(2, _translate("Form", "并联抵消-中"))
        self.combo_filter_frame.setItemText(3, _translate("Form", "并联抵消-重"))
        self.combo_filter_time.setItemText(0, _translate("Form", "无"))
        self.combo_filter_time.setItemText(1, _translate("Form", "RC-轻"))
        self.combo_filter_time.setItemText(2, _translate("Form", "RC-重"))
        self.combo_filter_time.setItemText(3, _translate("Form", "中值-短"))
        self.combo_filter_time.setItemText(4, _translate("Form", "中值-长"))
        self.combo_filter_time.setItemText(5, _translate("Form", "中值-极长"))
        self.combo_filter_time.setItemText(6, _translate("Form", "均值-短"))
        self.combo_filter_time.setItemText(7, _translate("Form", "均值-长"))
        self.combo_filter_time.setItemText(8, _translate("Form", "均值-极长"))
        self.label_7.setText(_translate("Form", "零点"))
        self.button_set_zero.setText(_translate("Form", "零点修正"))
        self.button_abandon_zero.setText(_translate("Form", "去除修正"))
        self.label.setText(_translate("Form", "中值"))
        self.label_3.setText(_translate("Form", "追踪点"))
        self.label_2.setText(_translate("Form", "识别结果"))

from pyqtgraph import GraphicsLayoutWidget
